#!/bin/bash
### BEGIN INIT INFO
# Provides: 		    plane-launcher.sh
# Required-Start:    	$local_fs $syslog $remote_fs
# Required-Stop:     	$local_fs $syslog $remote_fs
# Default-Start:     	2 3 4 5
# Default-Stop:      	0 1 6
# Short-Description: 	Start Plane Launcher Web App
# Description:		    Start Plane Launcher Web App in production environment on port 80
### END INIT INFO

case "$1" in 
start)
    /etc/init.d/plane-launcher.sh &
   echo $!>/var/run/plane-launcher.pid
   ;;
stop)
   pkill -P `cat /var/run/plane-launcher.pid`
   rm /var/run/plane-launcher.pid
   ;;
restart)
   $0 stop
   $0 start
   ;;
status)
   if [ -e /var/run/plane-launcher.pid ]; then
      echo plane-launcher service is running, pid=`cat /var/run/plane-launcher.pid`
   else
      echo plane-launcher service is NOT running
      exit 1
   fi
   ;;
*)
   echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0 